vcom ../src/IP/data_rom.vhd
vcom ../src/serial_data_generator.vhd
vcom ../src/sync_diff.vhd
vcom ../src/serial_to_parallel.vhd
vcom ../src/main_controller.vhd
vcom ../src/bin2bcd_12bit_sync.vhd
vcom ../src/bcd_to_7seg.vhd
vcom ../src/statistics_calc.vhd
vcom ../src/statistics_calc_tb.vhd
